import React,{useCallback,useEffect,useMemo,useState} from 'react';
import {Activity,AlertTriangle,Database,FileCheck2,History,RefreshCw,ShieldCheck,Upload} from 'lucide-react';
import type {AdminRoles} from '../../../utils/adminUtils';
import {changeDataQualityIssueStatus,listDataQualityIssues,listImpactDrafts,listPublicDataAudit,listPublicDataSources,listPublicDataSyncRuns,loadPublicDataOverview,publishImpactDraft,rejectImpactDraft,runStatisticsImport} from '../../../services/publicDataAdminService';
import type {DataQualityIssue,ImpactDraft,PublicDataAuditEntry,PublicDataSyncRun,StatisticsImportPreview} from '../../../types/publicDataAdmin';

type Tab='overview'|'sync'|'import'|'quality'|'impact'|'sources'|'audit';
const TABS:Array<{id:Tab;label:string;path:string;icon:React.ReactNode}>=[
  {id:'overview',label:'Data Health',path:'/admin',icon:<ShieldCheck size={15}/>},{id:'sync',label:'Sync',path:'/admin/sync',icon:<RefreshCw size={15}/>},{id:'import',label:'통계 Import',path:'/admin/statistics/import',icon:<Upload size={15}/>},{id:'quality',label:'데이터 품질',path:'/admin/data-quality',icon:<AlertTriangle size={15}/>},{id:'impact',label:'Impact 승인',path:'/admin/impact',icon:<Activity size={15}/>},{id:'sources',label:'출처',path:'/admin/sources',icon:<Database size={15}/>},{id:'audit',label:'감사로그',path:'/admin/audit',icon:<History size={15}/>},
];
const initialTab=():Tab=>{const path=window.location.pathname;if(path.includes('/statistics/import'))return'import';if(path.endsWith('/sync'))return'sync';if(path.endsWith('/data-quality'))return'quality';if(path.endsWith('/impact'))return'impact';if(path.endsWith('/sources'))return'sources';if(path.endsWith('/audit'))return'audit';return'overview';};
const date=(value:string|null|undefined)=>value?new Date(value).toLocaleString('ko-KR'):'-';

export default function PublicDataOperations({roles}:{roles:AdminRoles}){
  const canRead=roles.systemAdmin||roles.seniorModerator||roles.agencyOperator||roles.reportModerator;
  const canOperate=roles.systemAdmin||roles.seniorModerator||roles.agencyOperator;
  const canPublish=roles.systemAdmin||roles.seniorModerator;
  const [tab,setTab]=useState<Tab>(initialTab);
  const [loading,setLoading]=useState(false);const[error,setError]=useState('');
  const[overview,setOverview]=useState<any>(null);const[runs,setRuns]=useState<PublicDataSyncRun[]>([]);const[issues,setIssues]=useState<DataQualityIssue[]>([]);const[drafts,setDrafts]=useState<ImpactDraft[]>([]);const[sources,setSources]=useState<any[]>([]);const[audit,setAudit]=useState<PublicDataAuditEntry[]>([]);
  const[file,setFile]=useState<File|null>(null);const[encoding,setEncoding]=useState<'cp949'|'utf8'>('cp949');const[cutoff,setCutoff]=useState('');const[officialUrl,setOfficialUrl]=useState('');const[preview,setPreview]=useState<StatisticsImportPreview|null>(null);const[importReason,setImportReason]=useState('');const[previewConfirmed,setPreviewConfirmed]=useState(false);
  const[actionTarget,setActionTarget]=useState<{kind:'issue'|'publish'|'reject';id:string}|null>(null);const[actionReason,setActionReason]=useState('');
  const activeMeta=useMemo(()=>TABS.find((item)=>item.id===tab)!,[tab]);

  const load=useCallback(async(signal?:AbortSignal)=>{if(!canRead)return;setLoading(true);setError('');try{if(tab==='overview')setOverview(await loadPublicDataOverview(signal));if(tab==='sync')setRuns(await listPublicDataSyncRuns(signal));if(tab==='quality')setIssues(await listDataQualityIssues(signal));if(tab==='impact')setDrafts(await listImpactDrafts(signal));if(tab==='sources')setSources(await listPublicDataSources(signal));if(tab==='audit')setAudit(await listPublicDataAudit(signal));}catch(err){if(!signal?.aborted)setError(err instanceof Error?err.message:'운영 데이터를 불러오지 못했습니다.');}finally{if(!signal?.aborted)setLoading(false);}},[canRead,tab]);
  useEffect(()=>{const controller=new AbortController();void load(controller.signal);return()=>controller.abort();},[load]);
  useEffect(()=>{const onPop=()=>setTab(initialTab());window.addEventListener('popstate',onPop);return()=>window.removeEventListener('popstate',onPop);},[]);
  const navigate=(next:Tab)=>{const meta=TABS.find((item)=>item.id===next)!;window.history.pushState({},'',meta.path);setTab(next);setError('');};
  const previewImport=async()=>{if(!file)return;setLoading(true);setError('');try{setPreview(await runStatisticsImport(file,{encoding,dryRun:true,datasetCutoff:cutoff,officialPageUrl:officialUrl}));setPreviewConfirmed(false);}catch(err){setError(err instanceof Error?err.message:'CSV dry-run 실패');}finally{setLoading(false);}};
  const applyImport=async()=>{if(!file||!preview||!previewConfirmed||importReason.trim().length<3)return;setLoading(true);setError('');try{const result=await runStatisticsImport(file,{encoding,dryRun:false,datasetCutoff:cutoff,officialPageUrl:officialUrl,reason:importReason});setPreview(result);setPreviewConfirmed(false);await load();}catch(err){setError(err instanceof Error?err.message:'통계 import 실패');}finally{setLoading(false);}};
  const submitAction=async(status?:'investigating'|'resolved'|'ignored')=>{if(!actionTarget||actionReason.trim().length<3)return;setLoading(true);setError('');try{if(actionTarget.kind==='issue'&&status)await changeDataQualityIssueStatus(actionTarget.id,status,actionReason);if(actionTarget.kind==='publish')await publishImpactDraft(actionTarget.id,actionReason);if(actionTarget.kind==='reject')await rejectImpactDraft(actionTarget.id,actionReason);setActionTarget(null);setActionReason('');await load();}catch(err){setError(err instanceof Error?err.message:'운영 변경 실패');}finally{setLoading(false);}};

  if(!canRead)return <section className="mb-6 rounded-2xl border border-amber-200 bg-amber-50 p-6"><h2 className="text-lg font-black text-amber-950">공공데이터 운영 권한 없음</h2><p className="mt-2 text-sm leading-6 text-amber-900">reportModerator, agencyOperator, seniorModerator 또는 systemAdmin 역할이 필요합니다. privacyOfficer 역할만으로는 이 운영 데이터에 접근할 수 없습니다.</p></section>;
  return <section className="mb-6 overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-sm" aria-labelledby="public-data-operations-title">
    <div className="border-b border-slate-200 bg-[#10213a] p-5 text-white"><div className="flex flex-wrap items-center justify-between gap-3"><div><p className="text-xs font-black tracking-[0.16em] text-cyan-300">PUBLIC DATA OPERATIONS</p><h2 id="public-data-operations-title" className="mt-1 text-xl font-black">공공데이터·Impact 운영</h2><p className="mt-1 text-xs text-slate-300">조회는 역할 기반, 모든 변경은 서버 검증과 감사로그를 거칩니다.</p></div><button type="button" onClick={()=>void load()} disabled={loading} className="inline-flex items-center gap-1 rounded-lg bg-white/10 px-3 py-2 text-xs font-black disabled:opacity-50"><RefreshCw size={14}/>새로고침</button></div></div>
    <div role="tablist" aria-label="공공데이터 운영 메뉴" className="flex gap-1 overflow-x-auto border-b border-slate-200 bg-slate-50 p-2">{TABS.map((item)=><button key={item.id} role="tab" aria-selected={tab===item.id} type="button" onClick={()=>navigate(item.id)} className={`flex shrink-0 items-center gap-1 rounded-lg px-3 py-2 text-xs font-black ${tab===item.id?'bg-[#1e3a5f] text-white':'bg-white text-slate-600 hover:text-slate-950'}`}>{item.icon}{item.label}</button>)}</div>
    <div className="p-5"><div className="mb-4 flex items-center justify-between"><h3 className="font-black text-slate-950">{activeMeta.label}</h3>{loading&&<span role="status" className="text-xs font-bold text-slate-500">처리 중…</span>}</div>{error&&<div role="alert" className="mb-4 rounded-lg border border-red-200 bg-red-50 p-3 text-sm text-red-900">{error}</div>}
      {tab==='overview'&&<div className="grid gap-3 sm:grid-cols-3"><article className="rounded-xl border border-slate-200 p-4"><span className="text-xs font-bold text-slate-500">열린 데이터품질 이슈</span><strong className="mt-2 block text-2xl text-slate-950">{overview?.openIssueCount??'-'}</strong></article><article className="rounded-xl border border-slate-200 p-4 sm:col-span-2"><span className="text-xs font-bold text-slate-500">최신 Impact draft</span><strong className="mt-2 block text-lg text-slate-950">{overview?.latestImpactDraft?.month||'없음'}</strong><p className="mt-1 text-xs text-slate-500">상태 {overview?.latestImpactDraft?.review?.state||'-'} · 이상치 {overview?.latestImpactDraft?.anomalies?.length||0}건</p></article>{Object.entries(overview?.latestByType||{}).map(([type,run]:any)=><article key={type} className="rounded-xl bg-slate-50 p-4"><span className="text-xs font-bold text-slate-500">{type}</span><strong className="mt-1 block text-sm text-slate-950">{run.status}</strong><p className="mt-1 text-xs text-slate-500">{date(run.completedAt||run.startedAt)}</p></article>)}</div>}
      {tab==='sync'&&<div className="overflow-x-auto"><table className="min-w-full text-sm"><thead className="bg-slate-50 text-left text-xs text-slate-600"><tr><th className="px-3 py-2">시작</th><th className="px-3 py-2">유형</th><th className="px-3 py-2">상태</th><th className="px-3 py-2">수신/변경/실패</th><th className="px-3 py-2">hash</th></tr></thead><tbody>{runs.map((run)=><tr key={run.id} className="border-t border-slate-100"><td className="px-3 py-2">{date(run.startedAt)}</td><td className="px-3 py-2 font-bold">{run.type}</td><td className="px-3 py-2">{run.status}</td><td className="px-3 py-2">{run.counts?`${run.counts.receivedRows||0}/${(run.counts.created||0)+(run.counts.updated||0)}/${run.counts.failed||0}`:'-'}</td><td className="px-3 py-2 font-mono text-xs">{run.sourceHashPrefix||'-'}</td></tr>)}</tbody></table></div>}
      {tab==='import'&&<div className="space-y-4"><div className="grid gap-3 md:grid-cols-2"><label className="text-xs font-bold text-slate-700">경찰청 CSV<input type="file" accept=".csv,text/csv" onChange={(event)=>{setFile(event.target.files?.[0]||null);setPreview(null);}} className="mt-1 block w-full rounded-lg border border-slate-200 p-2 text-sm"/></label><label className="text-xs font-bold text-slate-700">인코딩<select value={encoding} onChange={(event)=>setEncoding(event.target.value as any)} className="mt-1 block w-full rounded-lg border border-slate-200 p-2 text-sm"><option value="cp949">CP949</option><option value="utf8">UTF-8</option></select></label><label className="text-xs font-bold text-slate-700">데이터 기준일<input type="date" value={cutoff} onChange={(event)=>setCutoff(event.target.value)} className="mt-1 block w-full rounded-lg border border-slate-200 p-2 text-sm"/></label><label className="text-xs font-bold text-slate-700">공식 페이지 URL<input type="url" value={officialUrl} onChange={(event)=>setOfficialUrl(event.target.value)} className="mt-1 block w-full rounded-lg border border-slate-200 p-2 text-sm"/></label></div><button type="button" disabled={!file||loading||!canOperate} onClick={()=>void previewImport()} className="inline-flex items-center gap-1 rounded-lg bg-[#1e3a5f] px-4 py-2 text-sm font-black text-white disabled:opacity-50"><FileCheck2 size={15}/>변경 미리보기</button>{preview&&<div className="rounded-xl border border-blue-200 bg-blue-50 p-4"><p className="text-sm font-black text-blue-950">{preview.status} · {preview.years.join(', ')}년</p><p className="mt-1 text-xs text-blue-900">신규 {preview.created} · 변경 {preview.updated} · 동일 {preview.unchanged} · hash {preview.sourceHash.slice(0,12)}…</p>{preview.warnings.length>0&&<ul className="mt-2 text-xs text-amber-900">{preview.warnings.map((warning)=><li key={warning}>• {warning}</li>)}</ul>}<label className="mt-4 flex items-start gap-2 text-xs font-bold text-blue-950"><input type="checkbox" checked={previewConfirmed} onChange={(event)=>setPreviewConfirmed(event.target.checked)}/>위 변경 미리보기와 경고를 확인했습니다.</label><label className="mt-3 block text-xs font-bold text-blue-950">적용 사유<textarea value={importReason} onChange={(event)=>setImportReason(event.target.value)} maxLength={500} className="mt-1 block w-full rounded-lg border border-blue-200 bg-white p-2 text-sm"/></label><button type="button" disabled={!canOperate||!previewConfirmed||importReason.trim().length<3||loading} onClick={()=>void applyImport()} className="mt-3 rounded-lg bg-red-700 px-4 py-2 text-sm font-black text-white disabled:opacity-50">확정 Import</button></div>}</div>}
      {tab==='quality'&&<div className="space-y-3">{issues.length===0&&<p className="rounded-xl bg-slate-50 p-4 text-sm text-slate-600">열린 이슈가 없습니다.</p>}{issues.map((issue)=><article key={issue.id} className="rounded-xl border border-slate-200 p-4"><div className="flex flex-wrap items-start justify-between gap-2"><div><span className="text-xs font-black text-amber-700">{issue.type} · {issue.severity}</span><h4 className="mt-1 font-black text-slate-950">{issue.code}</h4><p className="mt-1 text-xs text-slate-500">{issue.target} · {date(issue.createdAt)}</p></div>{canOperate&&<button type="button" onClick={()=>{setActionTarget({kind:'issue',id:issue.id});setActionReason('');}} className="rounded-lg border border-slate-200 px-3 py-2 text-xs font-black">처리</button>}</div></article>)}</div>}
      {tab==='impact'&&<div className="space-y-3">{drafts.length===0&&<p className="rounded-xl bg-slate-50 p-4 text-sm text-slate-600">Impact draft가 없습니다.</p>}{drafts.map((draft)=><article key={draft.month} className="rounded-xl border border-slate-200 p-4"><div className="flex flex-wrap items-start justify-between gap-3"><div><h4 className="text-lg font-black text-slate-950">{draft.month}</h4><p className="mt-1 text-xs text-slate-500">상태 {draft.review?.state||'draft'} · 노출 {(draft.events?.caseImpressions||0).toLocaleString()}회 · 이상치 {draft.anomalies?.length||0}건</p><p className="mt-1 text-xs text-slate-500">raw 검증 {String(draft.aggregation?.rawMonthlyValidated===true?'완료':'미완료')}</p></div>{canPublish&&<div className="flex gap-2"><button type="button" onClick={()=>{setActionTarget({kind:'publish',id:draft.month});setActionReason('');}} className="rounded-lg bg-emerald-700 px-3 py-2 text-xs font-black text-white">승인</button><button type="button" onClick={()=>{setActionTarget({kind:'reject',id:draft.month});setActionReason('');}} className="rounded-lg bg-red-700 px-3 py-2 text-xs font-black text-white">반려</button></div>}</div></article>)}</div>}
      {tab==='sources'&&<div className="grid gap-3 md:grid-cols-2">{sources.map((source)=><article key={source.id} className="rounded-xl border border-slate-200 p-4"><div className="flex items-center gap-2"><Database size={16} className="text-[#1e3a5f]"/><h4 className="font-black text-slate-950">{source.title||source.id}</h4></div><p className="mt-2 text-xs text-slate-500">{source.agency} · {source.sourceType||'unknown'} · {source.enabled?'활성':'중지'}</p><p className="mt-1 text-xs text-slate-500">마지막 확인 {date(source.lastCheckedAt)} · hash {source.lastHashPrefix||'-'}</p></article>)}</div>}
      {tab==='audit'&&<div className="overflow-x-auto"><table className="min-w-full text-sm"><thead className="bg-slate-50 text-left text-xs text-slate-600"><tr><th className="px-3 py-2">시각</th><th className="px-3 py-2">역할</th><th className="px-3 py-2">작업</th><th className="px-3 py-2">대상</th><th className="px-3 py-2">사유</th></tr></thead><tbody>{audit.map((entry)=><tr key={entry.id} className="border-t border-slate-100"><td className="px-3 py-2">{date(entry.createdAt)}</td><td className="px-3 py-2">{entry.actorRole}</td><td className="px-3 py-2 font-bold">{entry.action}</td><td className="px-3 py-2 font-mono text-xs">{entry.target}</td><td className="px-3 py-2">{entry.reason||'-'}</td></tr>)}</tbody></table></div>}
    </div>
    {actionTarget&&<div className="border-t border-slate-200 bg-slate-50 p-5" role="dialog" aria-label="운영 변경 확인"><h3 className="font-black text-slate-950">{actionTarget.kind==='publish'?'Impact 공개 승인':actionTarget.kind==='reject'?'Impact 반려':'데이터품질 이슈 처리'}</h3><label className="mt-3 block text-xs font-bold text-slate-700">판단 근거<textarea autoFocus value={actionReason} onChange={(event)=>setActionReason(event.target.value)} maxLength={500} className="mt-1 block w-full rounded-lg border border-slate-200 bg-white p-2 text-sm"/></label><div className="mt-3 flex flex-wrap gap-2">{actionTarget.kind==='issue'&&<><button type="button" onClick={()=>void submitAction('investigating')} disabled={actionReason.trim().length<3} className="rounded-lg bg-blue-700 px-3 py-2 text-xs font-black text-white disabled:opacity-50">조사 중</button><button type="button" onClick={()=>void submitAction('resolved')} disabled={actionReason.trim().length<3} className="rounded-lg bg-emerald-700 px-3 py-2 text-xs font-black text-white disabled:opacity-50">해결</button><button type="button" onClick={()=>void submitAction('ignored')} disabled={actionReason.trim().length<3} className="rounded-lg bg-slate-700 px-3 py-2 text-xs font-black text-white disabled:opacity-50">무시</button></>}{actionTarget.kind!=='issue'&&<button type="button" onClick={()=>void submitAction()} disabled={actionReason.trim().length<3} className="rounded-lg bg-[#10213a] px-3 py-2 text-xs font-black text-white disabled:opacity-50">사유와 함께 확정</button>}<button type="button" onClick={()=>setActionTarget(null)} className="rounded-lg border border-slate-200 bg-white px-3 py-2 text-xs font-black">취소</button></div></div>}
  </section>;
}
